import { AITool } from './types';

export const TOOLS_DATA: AITool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    nameEn: 'ChatGPT',
    description: 'OpenAI开发的AI对话助手',
    descriptionForAI: 'ChatGPT是OpenAI开发的强大AI对话系统。基于GPT-4模型，可以进行自然语言对话、代码编写、知识问答等多种任务。是目前最流行的AI助手之一。',
    category: 'AI对话',
    subcategory: 'LLM',
    capabilities: ['对话', '代码生成', '文本创作', '知识问答'],
    website: 'https://chat.openai.com',
    pricing: {
      hasFreeTier: true,
      startingPrice: 20,
      pricingModel: 'per-month'
    },
    difficulty: 'easy',
    tags: ['AI对话', 'GPT-4', 'OpenAI', '智能助手'],
    useCases: ['日常问答', '代码编写', '文章创作', '学习辅导'],
    examples: ['帮我写一段Python代码', '解释什么是机器学习', '帮我写一封商务邮件'],
    openclawCompatible: true,
    popularity: 100,
    rating: 4.9,
    lastUpdated: '2026-05-20'
  },
  {
    id: 'claude',
    name: 'Claude',
    nameEn: 'Claude',
    description: 'Anthropic开发的AI助手，擅长分析',
    descriptionForAI: 'Claude是Anthropic公司的AI助手，擅长分析、写作和编程。支持超长上下文，可以处理长文档。提供Claude 3多个版本，从快速到超强性能可选。',
    category: 'AI对话',
    subcategory: 'LLM',
    capabilities: ['对话', '文档分析', '代码审查', '创意写作'],
    website: 'https://claude.ai',
    pricing: {
      hasFreeTier: true,
      startingPrice: 18,
      pricingModel: 'per-month'
    },
    difficulty: 'easy',
    tags: ['AI对话', 'Claude', 'Anthropic', '长文本'],
    useCases: ['文档分析', '代码审查', '深度写作', '研究辅助'],
    examples: ['分析这份PDF文档', '帮我审查这段代码', '写一个产品需求文档'],
    openclawCompatible: true,
    popularity: 95,
    rating: 4.8,
    lastUpdated: '2026-05-15'
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    nameEn: 'Midjourney',
    description: 'AI图像生成工具',
    descriptionForAI: 'Midjourney是通过Discord使用的AI图像生成工具。用户输入文字描述，它能生成精美图片。适合概念设计、插画创作等场景。支持多种艺术风格。',
    category: 'AI图像',
    subcategory: '图像生成',
    capabilities: ['文字生图', '风格转换', '图像编辑', '变体生成'],
    website: 'https://www.midjourney.com',
    pricing: {
      hasFreeTier: true,
      freeCredits: 25,
      startingPrice: 10,
      pricingModel: 'per-month'
    },
    difficulty: 'easy',
    tags: ['AI绘画', '图像生成', '设计', '创意'],
    useCases: ['概念设计', '插画创作', '海报制作', '游戏素材'],
    examples: ['/imagine prompt: futuristic city at sunset', '生成一个可爱的机器人形象'],
    openclawCompatible: true,
    popularity: 98,
    rating: 4.8,
    lastUpdated: '2026-05-18'
  },
  {
    id: 'dalle',
    name: 'DALL-E 3',
    nameEn: 'DALL-E 3',
    description: 'OpenAI开发的AI图像生成模型',
    descriptionForAI: 'DALL-E 3是OpenAI的第三代图像生成模型。能准确理解复杂的文字描述并生成对应图像。对细节和文字的处理非常精准，适合商业图片生成。',
    category: 'AI图像',
    subcategory: '图像生成',
    capabilities: ['文字生图', '图像编辑', '变体生成', '精确渲染'],
    website: 'https://openai.com/dall-e-3',
    pricing: {
      hasFreeTier: true,
      freeCredits: 5,
      startingPrice: 0.04,
      pricingModel: 'per-call'
    },
    difficulty: 'easy',
    tags: ['AI绘画', 'OpenAI', '图像生成', '商业图片'],
    useCases: ['产品图片', '营销素材', '概念图', '配图生成'],
    examples: ['生成一张科技公司CEO的肖像', '创建一个未来城市的插画'],
    openclawCompatible: true,
    popularity: 92,
    rating: 4.7,
    lastUpdated: '2026-05-12'
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    nameEn: 'Stable Diffusion',
    description: '开源的AI图像生成模型',
    descriptionForAI: 'Stable Diffusion是Stability AI开源的图像生成模型。可以本地部署或使用云服务。开源免费，支持丰富的自定义模型和插件生态。',
    category: 'AI图像',
    subcategory: '图像生成',
    capabilities: ['文字生图', '图像编辑', 'ControlNet', '模型定制'],
    website: 'https://stability.ai',
    pricing: {
      hasFreeTier: true,
      pricingModel: 'freemium'
    },
    difficulty: 'hard',
    tags: ['开源', 'AI绘画', '本地部署', '自定义模型'],
    useCases: ['本地开发', '批量生成', '模型定制', '研究实验'],
    examples: ['本地部署SDXL模型', '使用ControlNet控制构图'],
    openclawCompatible: true,
    popularity: 96,
    rating: 4.6,
    lastUpdated: '2026-05-10'
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    nameEn: 'GitHub Copilot',
    description: 'AI代码补全助手',
    descriptionForAI: 'GitHub Copilot是微软和OpenAI合作开发的AI编程助手。实时提供代码补全建议，支持多种编程语言。与VS Code等主流IDE深度集成。',
    category: 'AI编程',
    subcategory: '代码助手',
    capabilities: ['代码补全', '函数生成', '代码审查', 'Bug修复'],
    website: 'https://github.com/features/copilot',
    pricing: {
      hasFreeTier: false,
      startingPrice: 10,
      pricingModel: 'per-month'
    },
    difficulty: 'easy',
    tags: ['代码助手', '编程工具', 'IDE插件', '效率提升'],
    useCases: ['代码补全', '学习新语言', '代码重构', 'Bug修复'],
    examples: ['写一个Python装饰器', '用TypeScript实现防抖函数'],
    openclawCompatible: true,
    popularity: 97,
    rating: 4.6,
    lastUpdated: '2026-05-08'
  },
  {
    id: 'cursor',
    name: 'Cursor',
    nameEn: 'Cursor',
    description: 'AI原生的代码编辑器',
    descriptionForAI: 'Cursor是专门为AI协作设计的代码编辑器。基于VS Code内核，深度集成GPT-4。支持代码生成、编辑、聊天等多种AI功能。',
    category: 'AI编程',
    subcategory: '代码编辑器',
    capabilities: ['AI代码生成', '智能编辑', '代码解释', '项目级理解'],
    website: 'https://cursor.sh',
    pricing: {
      hasFreeTier: true,
      startingPrice: 20,
      pricingModel: 'per-month'
    },
    difficulty: 'easy',
    tags: ['代码编辑器', 'AI原生', 'VS Code', '智能编程'],
    useCases: ['日常编程', '项目开发', '代码学习', '快速原型'],
    examples: ['用Cursor重构整个项目', '让AI解释一段复杂代码'],
    openclawCompatible: true,
    popularity: 90,
    rating: 4.7,
    lastUpdated: '2026-05-14'
  },
  {
    id: 'runway',
    name: 'Runway',
    nameEn: 'Runway',
    description: 'AI视频生成和编辑平台',
    descriptionForAI: 'Runway是专注于视频和图像创作的AI平台。提供视频生成、编辑、特效等功能。Gen-2模型可以根据文本或图像生成视频。',
    category: 'AI视频',
    subcategory: '视频生成',
    capabilities: ['文字生视频', '图生视频', '视频编辑', '特效制作'],
    website: 'https://runwayml.com',
    pricing: {
      hasFreeTier: true,
      freeCredits: 125,
      startingPrice: 15,
      pricingModel: 'credits'
    },
    difficulty: 'medium',
    tags: ['AI视频', '视频生成', '视频编辑', '创意工具'],
    useCases: ['短视频创作', '视频特效', '概念视频', '社交媒体内容'],
    examples: ['生成一段海边日落视频', '将照片转换为动画'],
    openclawCompatible: true,
    popularity: 85,
    rating: 4.4,
    lastUpdated: '2026-05-11'
  },
  {
    id: 'eleven-labs',
    name: 'ElevenLabs',
    nameEn: 'ElevenLabs',
    description: 'AI语音合成平台',
    descriptionForAI: 'ElevenLabs专注于AI语音技术。能将文本转换为自然语音，支持多语言和多种音色。还提供语音克隆功能，可以用少量样本训练个性化声音。',
    category: 'AI音频',
    subcategory: '语音合成',
    capabilities: ['文字转语音', '语音克隆', '多语言', '情感控制'],
    website: 'https://elevenlabs.io',
    pricing: {
      hasFreeTier: true,
      freeCredits: 10000,
      startingPrice: 5,
      pricingModel: 'per-month'
    },
    difficulty: 'easy',
    tags: ['语音合成', 'TTS', '配音', '语音克隆'],
    useCases: ['视频配音', '有声书', '游戏配音', '语音助手'],
    examples: ['将这段文字转为中文语音', '克隆我的声音'],
    openclawCompatible: true,
    popularity: 88,
    rating: 4.7,
    lastUpdated: '2026-05-13'
  },
  {
    id: 'zapier',
    name: 'Zapier',
    nameEn: 'Zapier',
    description: '自动化工作流平台',
    descriptionForAI: 'Zapier是一个自动化平台，连接不同的应用和服务创建自动化工作流。支持5000+应用集成，可以用来构建AI驱动的自动化流程。',
    category: 'AI自动化',
    subcategory: '工作流',
    capabilities: ['流程自动化', '应用集成', '定时任务', 'AI触发'],
    website: 'https://zapier.com',
    pricing: {
      hasFreeTier: true,
      startingPrice: 19.99,
      pricingModel: 'per-month'
    },
    difficulty: 'medium',
    tags: ['自动化', '工作流', '集成', '效率工具'],
    useCases: ['数据同步', '自动通知', '社交管理', 'AI自动化'],
    examples: ['收到邮件自动总结发送到Slack', '定时生成AI报告'],
    openclawCompatible: true,
    popularity: 93,
    rating: 4.6,
    lastUpdated: '2026-05-09'
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    nameEn: 'Notion AI',
    description: 'Notion内置的AI助手',
    descriptionForAI: 'Notion AI是集成在Notion笔记工具中的AI助手。可以帮助写作、总结、头脑风暴等。与Notion的文档、数据库等功能深度集成。',
    category: 'AI办公',
    subcategory: '写作助手',
    capabilities: ['AI写作', '内容总结', '头脑风暴', '翻译'],
    website: 'https://notion.so',
    pricing: {
      hasFreeTier: true,
      startingPrice: 10,
      pricingModel: 'per-month'
    },
    difficulty: 'easy',
    tags: ['笔记', '写作助手', '办公', 'Notion'],
    useCases: ['写作辅助', '会议总结', '头脑风暴', '文档处理'],
    examples: ['帮我写一份项目报告', '总结这段会议记录'],
    openclawCompatible: true,
    popularity: 91,
    rating: 4.5,
    lastUpdated: '2026-05-16'
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    nameEn: 'Perplexity',
    description: 'AI驱动的搜索引擎',
    descriptionForAI: 'Perplexity是AI驱动的搜索引擎，可以理解问题并从网络获取最新信息进行回答。提供追问功能和来源引用，适合需要实时信息的场景。',
    category: 'AI搜索',
    subcategory: '搜索引擎',
    capabilities: ['智能搜索', '实时信息', '来源引用', '多轮对话'],
    website: 'https://perplexity.ai',
    pricing: {
      hasFreeTier: true,
      startingPrice: 20,
      pricingModel: 'per-month'
    },
    difficulty: 'easy',
    tags: ['搜索引擎', 'AI搜索', '实时信息', '研究工具'],
    useCases: ['信息检索', '市场调研', '技术支持', '学术研究'],
    examples: ['查找最新AI技术进展', '了解某个产品的最新动态'],
    openclawCompatible: true,
    popularity: 89,
    rating: 4.6,
    lastUpdated: '2026-05-17'
  }
];
